### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [PeterBooker/wpds#7]
Hello again @PeterBooker I wanted to logo designed for wpds and i designed a logo. What do you think this logo?

![wpds](https://user-images.githubusercontent.com/36298335/41941695-6d4ad5e6-79a5-11e8-8166-6f82a0ff96c0.jpg)

**Comment by PeterBooker** [comment]
Hey @reallinfo, thanks but this project is currently shelved in favour of the WPdirectory project you have already kindly contributed a logo to. I do not have anything else which would warrant a logo, but I wish you the best of luck on your quest to provide logos for the internet!
